Criar setores no backend
fga-eps-mds/2020-2-G4-Sectors pull request #2
Opened 2021-04-01 04:33 UTC by DafneM

closes fga-eps-mds/2020-2-G4#96
closes fga-eps-mds/2020-2-G4#97
closes fga-eps-mds/2020-2-G4#98
closes fga-eps-mds/2020-2-G4#99

## Descrição
Implementamos as funções de criar, deletar, atualizar e visualizar setores no backend, com seus respectivos testes.

2021-04-01 18:38 UTC, JPedroCh requested changes

2021-04-01 18:38 UTC, JPedroCh commented on src/Controllers/SectorController.js
> +};
A função está retornando apenas o primeiro setor armazenado.

2021-04-01 18:38 UTC, JPedroCh commented on tests/api.test.js
> +>>>>>>> 99-delete-sectors
É preciso escolher quais mudanças do rebase ficarão no arquivo e retirar os comentários.

2021-04-02 01:46 UTC, vitorl-s approved these changes
Ok!

2021-04-02 01:57 UTC, JPedroCh approved these changes
Ótimo trabalho!

2021-04-02 01:58 UTC, merged